# Generated by Django 4.1.7 on 2023-02-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='roomname',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='username',
            new_name='user',
        ),
    ]
