# Generated by Django 4.1.7 on 2023-02-21 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 21, 10, 40, 44, 255000, tzinfo=datetime.timezone.utc)),
        ),
    ]
